version: 2.33.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - openssl
skip_tags: true
os: Visual Studio 2015
shallow_clone: true
clone_depth: 1

# avoid building 32-bit if 64-bit failed already
matrix:
  fast_finish: true

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  MSYS2_PATH_TYPE: inherit
  CHERE_INVOKING: enabled_from_arguments
  matrix:
  - MSYSTEM: MINGW64
    MSYS_PACKAGES: mingw-w64-x86_64-boost mingw-w64-x86_64-miniupnpc
    MSYS_BITNESS: 64
  - MSYSTEM: MINGW32
    MSYS_PACKAGES: mingw-w64-i686-boost mingw-w64-i686-miniupnpc
    MSYS_BITNESS: 32

cache:
  - c:\msys64\var\cache\pacman\pkg\

install:
# install new signing keyring	
- c:\msys64\usr\bin\bash -lc "curl -O https://mirror.selfnet.de/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"	
- c:\msys64\usr\bin\bash -lc "curl -O https://mirror.selfnet.de/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"	
- c:\msys64\usr\bin\bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"	
- c:\msys64\usr\bin\bash -lc "pacman --noconfirm -U msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
# remove packages which can break build
- c:\msys64\usr\bin\bash -lc "pacman --noconfirm -Rns gcc-fortran gcc mingw-w64-{i686,x86_64}-gcc-ada mingw-w64-{i686,x86_64}-gcc-objc"
# update runtime
- c:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
# Kill bash before next try
- taskkill /T /F /IM bash.exe /IM gpg.exe /IM gpg-agent.exe | exit /B 0
# update packages and install required
- c:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu ${MSYS_PACKAGES}"

build_script:
- echo MSYSTEM = %MSYSTEM%, bitness = %MSYS_BITNESS%
- c:\msys64\usr\bin\bash -lc "make USE_UPNP=yes -j3"
- 7z a -tzip -mx9 -mmt i2pd-mingw-win%MSYS_BITNESS%.zip i2pd.exe

after_build:
- c:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sc"

test: off

deploy: off

artifacts:
- path: i2pd-mingw-win*.zip
