name: Build on FreeBSD

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    name: with UPnP
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.0.9
      with:
        usesh: true
        prepare: pkg install -y devel/gmake devel/boost-libs security/openssl net/miniupnpc 
        run: |
          make USE_UPNP=yes -j3
