name: Build on FreeBSD

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    name: A job to run test FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.0.9
      with:
        usesh: true
        prepare: pkg install -y make boost-libs ssl miniupnpc
        run: |
          make USE_UPNP=yes -j3
